# Generated by Django 5.1 on 2024-08-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='category',
            field=models.CharField(choices=[('Clothing & Apparel', 'Clothing & Apparel'), ('Electronics & Gadgets', 'Electronics & Gadgets'), ('Health & Beauty', 'Health & Beauty'), ('Home & Kitchen', 'Home & Kitchen'), ('Books & Media', 'Books & Media'), ('Sports & Outdoor', 'Sports & Outdoor')], max_length=50),
        ),
    ]
