# Generated by Django 5.1 on 2024-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
