# Generated by Django 5.1 on 2024-09-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userproduct_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproduct',
            old_name='image',
            new_name='image_url',
        ),
    ]
