# Generated by Django 5.1 on 2024-09-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_image_userproduct_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
