# Generated by Django 5.1 on 2024-09-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='selected_value',
            field=models.CharField(choices=[('Clothing & Apparel', 'Clothing & Apparel'), ('Electronics & Gadgets', 'Electronics & Gadgets'), ('Food Items', 'Food Items'), ('Home & Kitchen', 'Home & Kitchen'), ('Books & Media', 'Books & Media'), ('Sports & Outdoor', 'Sports & Outdoor')], default='Value1', max_length=50),
        ),
    ]
